### ISSUE TITLE
Allow people to assign me as a reviewer

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-layers-polyfill#15]
@himorin My coworker @dmliao is unable to add me as a reviewer.
Is this something you can enable? I don't see where I can do that on my side

**Comment by himorin** [comment]
Usually users linked to github organization (esp. w3c) is linked to w3c account (by join status of groups), but this immersive-web organization is not.
I've invited the account to member of this organization, after invitation accepted, I hope the account can edit more status of issues/PRs like reviewers or assignees.

**Comment by cabanier** [comment]
Thanks @himorin !

@dmliao , let me know if this solves the issue for you.

**Comment by dmliao** [comment]
It looks like I still can't assign people as reviewers on issues. I don't know if it'd be the same on a PR.

**Comment by cabanier** [comment]
@himorin I also can't assign reviewer on the [WebXR](https://github.com/immersive-web/webxr-hand-input and [WebXR Hands](https://github.com/immersive-web/webxr) repos.

**Comment by himorin** [comment]
Thank you for pointing. 
Checking around, I've found default permission for member is Read... Let me check with chairs on this.

**Comment by cabanier** [comment]
Yes, anyone should be able to request that their PR is reviewed.

**Comment by himorin** [comment]
issue still remains?

**Comment by cabanier** [comment]
No, yesterday @dmliao was able to send me a PR to review.

Thank you!
