### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by dmliao** [immersive-web/webxr-layers-polyfill#2]
The polyfill's build files should be importable from npm, akin to what we have for the webxr-polyfill.

The scripts in `package.json` are already set so that when `npm version <major / minor / patch>` is run, the build files are automatically added to the commit. We can then publish those files as a new package. However, there might be some fields in `package.json` to update before doing that, as I'm not personally familiar with the npm publishing workflow.

@Yonet @AdaRoseCannon @cabanier

**Comment by cabanier** [comment]
I assume this will be very similar to what was done for the WebXR polyfill: https://github.com/immersive-web/webxr-polyfill/blob/main/package.json

**Comment by AdaRoseCannon** [comment]
@toji do you have publishing permissions for npm? I don't think I do.

**Comment by cabanier** [comment]
@AdaRoseCannon is there someone in particular we need to contact?

**Comment by himorin** [comment]
I think there is only free registration just with your information (by `npm adduser`), and you can push your tag (on this repository) to npm with `npm publish` if it passes test and dependencies met.

**Comment by cabanier** [comment]
> I think there is only free registration just with your information (by `npm adduser`), and you can push your tag (on this repository) to npm with `npm publish` if it passes test and dependencies met.

Since I'm the owner of this repo, does that mean I need to do this?

**Comment by cabanier** [comment]
Als @himorin , what is my "tag"? Apart from `npm adduser`, what other commands should I run?

**Comment by himorin** [comment]
for who can do, I suppose anyone who can have access could, but I haven't tried on non-owner repo (actually owner of this is immersive-web organization...).
for tag, it's git tag (also npm has its own tagging also). please refer something like https://medium.com/@barberdt/understanding-npm-versioning-with-git-tags-ce669fc93dbb

I think following command lists should work (or what I've tried):

```
git tag -a v1.0.0 -m "tag version 1.0.0"
git push origin tags/v1.0.0
npm publish ./
```

**Comment by cabanier** [comment]
Thanks @himorin!

**Comment by cabanier** [comment]
The polyfill is now available on https://www.npmjs.com/package/webxr-layers-polyfill
