### ISSUE TITLE
[Crit] Invalid internal format

### ISSUE THREAD

**Issue by eXponenta** [immersive-web/webxr-layers-polyfill#26]
Internal format for SRGB must be RGB/RGBA in this line:
https://github.com/immersive-web/webxr-layers-polyfill/blob/e26ac846cb5e756daf8da9d03b1d373f6741bd0d/src/api/XRCompositionLayerPolyfill.ts#L448

Otherwise for sRGB textures will be invalid format error
<img width="955" alt="Снимок экрана 2022-06-06 в 18 31 46" src="https://user-images.githubusercontent.com/12572222/172193774-cab3b28b-7172-4ba9-bcb2-f52231e9306b.png">

**Comment by dmliao** [comment]
Fixed by #27, and expanded upon in #34. Thanks!
