### ISSUE TITLE
Add CDN link

### ISSUE THREAD

**Issue by dmliao** [immersive-web/webxr-layers-polyfill#3]
This involves both:

1. Publishing the polyfill's built files to a cdn, and
2. adding the link to the README.

We use jsdelivr for the webxr-polyfill, which I think automatically populates from the npm package, so this may be as simple as the README link once the package is published.

**Comment by cabanier** [comment]
Pushing to npm automatically generated a link to a CDN: https://cdn.jsdelivr.net/npm/webxr-layers-polyfill@1.0.0/build/webxr-layers-polyfill.js
