### ISSUE TITLE
Question: Projection layer with video

### ISSUE THREAD

**Issue by lukehb** [immersive-web/webxr-layers-polyfill#42]
Hi @cabanier 

**Context**
I am working on Pixel Streaming in Unreal Engine and we are rendering a left-right stereo backbuffer from UE, streaming it over WebRTC as a video, then displaying that video in a VR headset using WebXR layers. We also stream the HMD transform back to UE to drive the mock HMD on the UE side. Giving us a full VR experience rendered on a remote machine.

Anyway, currently we are displaying this video using the quad layer. We then orient the quad layer to match the user's HMD and take up their full field of view. However, it seems to me this is a more suitable job for a projection layer; however, they do not take video as input.

We can of course render that video into the WebGL texture and copy that texture into the projection layer; however, I am doubtful that we will enjoy the same performance/quality benefits offered by using the media layers?

**Question**
Do I have any better options than what I am currently doing?

Regards, Luke.

**Comment by cabanier** [comment]
A projection layer is basically a quad layer that fills the entire FOV and has the viewer space.
Your current approach is totally fine :-)

**Comment by lukehb** [comment]
Thanks Rik.

Out of interest, is this assumption of mine true:

> We can of course render that video into the WebGL texture and copy that texture into the projection layer; however, I am doubtful that we will enjoy the same performance/quality benefits offered by using the media layers?

**Comment by cabanier** [comment]
> Thanks Rik.
> 
> Out of interest, is this assumption of mine true:
> 
> > We can of course render that video into the WebGL texture and copy that texture into the projection layer; however, I am doubtful that we will enjoy the same performance/quality benefits offered by using the media layers?

Yes, we play a couple of tricks internally that you don't have access to through WebGL. Cross-origin video will also work with media layers.
