### ISSUE TITLE
Polyfill does not always leave webGL context in a good state.

### ISSUE THREAD

**Issue by dmliao** [immersive-web/webxr-layers-polyfill#8]
Seen when trying to add the polyfill to https://github.com/toji/xr-critter, or to the A-frame composition layers demo, we sometimes have geometry behaving oddly (using the wrong position array buffer), or textures being displayed on incorrect objects. 

Example: the hairbrush in xr-critter (note the left hairbrush's bristles turning into a cube):

![image](https://user-images.githubusercontent.com/769957/117368994-26ca4c80-ae79-11eb-9cbb-f61781c0635e.png)

This could be the result of improperly setting GL state, but exactly where the problem is stemming from is yet unknown.

**Comment by dmliao** [comment]
Addendum: This is a screenshot of the A-frame compositional layers demo failing to render the proper texture on the ground when the polyfill is active. Note that this only seems to happen if both the controllers and the UI elements (the quad layer) are not visible - as soon as controllers come back into view, this problem disappears:

![image](https://user-images.githubusercontent.com/769957/117372306-2d0ef780-ae7e-11eb-836c-a61998951d4c.png)

**Comment by cabanier** [comment]
@dmliao and I were stepping through this issue and it seems the aframe one is separate from the state problem we're seeing with xrpet.
I'll move that to a different one.
