### ISSUE TITLE
aframe example has drawing glitches with layers polyfill

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr-layers-polyfill#9]
The aframe layers samples (https://aframe.io/aframe/examples/test/layer/index.html) shows flickering.
When adding the polyfill, it stops rendering the ground when the controllers are not in the scene.
![117372306-2d0ef780-ae7e-11eb-836c-a61998951d4c](https://user-images.githubusercontent.com/1513308/117374928-ed96da00-ae82-11eb-90ed-a21e5502c8b0.png)

**Comment by dmliao** [comment]
This should now be fixed with #17
